title: Vahidin Jupic
logo: /assets/images/image1.png
description: Data Scientist with expertise in machine learning, data analysis, and operations research. Passionate about transforming data into actionable insights.

highlights:
  - Created a detailed cost estimates from disparate data, aiding successful bids for a $1.5 billion government contract.  
  - Identified potential savings exceeding $300M by modeling and evaluating alternative courses of action.  
  - Conducted novel research in physics by applying advanced mathematical modeling and Python simulations.  
  - Earned the Achievement Medal for Civilian Service for improving data verification processes.
  - Conducted cost-benefit analyses impacting billions in lifecycle costs for the Stryker combat system.

show_downloads: false
theme: jekyll-theme-minimal
